name: Build STL Models

on:
  push:
    paths:
      - 'scad/**/*.scad'
      - '.github/workflows/build-stl.yml'
  pull_request:
    paths:
      - 'scad/**/*.scad'
      - '.github/workflows/build-stl.yml'

jobs:
  build-stl:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Install OpenSCAD
        run: |
          sudo apt-get update
          sudo apt-get install -y openscad

      - name: Verify OpenSCAD installation
        run: openscad --version

      - name: Generate STL files
        run: |
          # create output root
          mkdir -p stl
          # iterate over all scad files and export to mirrored path under stl/
          find scad -type f -name '*.scad' | while read -r scad; do
            rel_path="${scad#scad/}"
            dir_name="$(dirname "$rel_path")"
            base_name="$(basename "$scad" .scad)"
            mkdir -p "stl/$dir_name"
            openscad -o "stl/$dir_name/${base_name}.stl" "$scad"
          done

      - name: List generated STLs
        run: |
          find stl -name '*.stl' -print

      - name: Upload STL artifacts
        uses: actions/upload-artifact@v4
        with:
          name: stl-models
          path: stl/**/*
          retention-days: 30

      - name: Commit updated STL files
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add stl/**/*
          if git diff --staged --quiet; then
            echo "No STL changes to commit"
          else
            git commit -m "🤖 Auto-generate STL files from OpenSCAD source"
            git push
          fi 